// Generated by CoffeeScript 1.3.1
(function() {
  var HEAPSIZE, buf;

  HEAPSIZE = 1024 * 1024;

  buf = new ArrayBuffer(HEAPSIZE);

  exports.I8 = new Int8Array(buf);

  exports.U8 = new Uint8Array(buf);

  exports.I16 = new Int16Array(buf);

  exports.U16 = new Uint16Array(buf);

  exports.I32 = new Int32Array(buf);

  exports.U32 = new Uint32Array(buf);

  exports.F32 = new Float32Array(buf);

  exports.F64 = new Float64Array(buf);

  exports.U32[0] = 8;

  exports.U32[1] = HEAPSIZE;

}).call(this);
