// Generated by CoffeeScript 1.3.1
(function() {
  var HEAPSIZE, buf;

  HEAPSIZE = 1024 * 1024;

  buf = new ArrayBuffer(HEAPSIZE);

  exports._I8 = new Int8Array(buf);

  exports._U8 = new Uint8Array(buf);

  exports._I16 = new Int16Array(buf);

  exports._U16 = new Uint16Array(buf);

  exports._I32 = new Int32Array(buf);

  exports._U32 = new Uint32Array(buf);

  exports._U32[0] = 8;

  exports._U32[1] = HEAPSIZE;

}).call(this);
