// Generated by CoffeeScript 1.3.1
(function() {
  var NALLOC, free, freep, malloc, morecore,
    _HEAP = require('heap/heap');

  // type header = struct { [0] ptr :: *header, [4] size :: u32 }

  // freep :: *header

  freep = 0;

  // malloc :: (u32) -> *any

  malloc = function(nbytes) { // :: (u32)
    var nunits, p, prevp,
      _U32 = _HEAP.U32;
    // p :: *header
    // prevp :: *header
    // nunits :: u32
    nunits = (nbytes + 8 - 1) / 8 + 1 >>> 0;
    if (!(prevp = freep)) {
      prevp = freep = _U32[0] >> 2;
      _U32[0] += 8;
      _U32[freep] = freep;
      _U32[freep + 1] = 0;
    }
    p = _U32[prevp];
    while (true) {
      if (_U32[p + 1] >= nunits) {
        if (_U32[p + 1] === nunits) {
          _U32[prevp] = _U32[p];
        } else {
          _U32[p + 1] -= nunits;
          p = p + (_U32[p + 1] << 1);
          _U32[p + 1] = nunits;
        }
        freep = prevp;
        return p + (1 << 1);
      }
      if (p === freep) {
        if (!(p = morecore(nunits))) {
          return 0;
        }
      }
      prevp = p;
      p = _U32[p];
    }
    return 0;
  };

  // NALLOC :: i32

  NALLOC = 1024;

  // morecore :: (u32) -> *header

  morecore = function(nu) { // :: (u32)
    var bytesNeeded, up,
      _U32 = _HEAP.U32;
    if (nu < NALLOC) {
      nu = NALLOC >>> 0;
    }
    bytesNeeded = nu * 8;
    if (_U32[0] + bytesNeeded >= _U8.length) {
      return 0;
    }
    // up :: *header
    up = _U32[0] >> 2;
    _U32[up + 1] = nu;
    _U32[0] += bytesNeeded;
    free(up + (1 << 1));
    return freep;
  };

  // free :: (*any) -> any

  free = function(ap) { // :: (*any)
    var bp, p,
      _U32 = _HEAP.U32;
    // bp :: *header
    // p :: *header
    bp = (ap >> 2) - (1 << 1);
    p = freep;
    while (!(bp > p && bp < _U32[p])) {
      if (p >= _U32[p] && (bp > p || bp < _U32[p])) {
        break;
      }
      p = _U32[p];
    }
    if ((bp + (_U32[bp + 1] << 1) === _U32[p])) {
      _U32[bp + 1] += _U32[_U32[p] + 1];
      _U32[bp] = _U32[_U32[p]];
    } else {
      _U32[bp] = _U32[p];
    }
    if ((p + (_U32[p + 1] << 1) === bp)) {
      _U32[p + 1] += _U32[bp + 1];
      _U32[p] = _U32[bp];
    } else {
      _U32[p] = bp;
    }
    freep = p;
  };

  exports.malloc = malloc;

  exports.free = free;

}).call(this);
