// Generated by CoffeeScript 1.3.1
(function() {
  var NALLOC, free, freep, malloc, morecore, _I16, _I32, _I8, _U16, _U32, _U8, _ref;

  _ref = require('./heap'), _I8 = _ref._I8, _U8 = _ref._U8, _I16 = _ref._I16, _U16 = _ref._U16, _I32 = _ref._I32, _U32 = _ref._U32;

  // type header = struct { [0] ptr :: *header, [4] size :: uint }

  // freep :: *header

  freep = null;

  // malloc :: (uint) -> *any

  malloc = function(nbytes) { // :: (uint)
    var nunits, p, prevp;
    // p, prevp :: *header
    // nunits :: uint
    nunits = ((nbytes + 8 - 1) / 8 + 1) >> 0;
    if (!(prevp = freep)) {
      prevp = freep = _U32[0] >> 2;
      _U32[0] += 8;
      _U32[freep] = freep;
      _U32[freep + 1] = 0;
    }
    p = _U32[prevp];
    while (true) {
      if (_U32[p + 1] >= nunits) {
        if (_U32[p + 1] === nunits) {
          _U32[prevp] = _U32[p];
        } else {
          _U32[p + 1] -= nunits;
          p += _U32[p + 1] * 2;
          _U32[p + 1] = nunits;
        }
        freep = prevp;
        return p + 1 * 2 << 2;
      }
      if (p === freep) {
        if (!(p = morecore(nunits))) {
          return null;
        }
      }
      prevp = p;
      p = _U32[p];
    }
    return null;
  };

  // NALLOC :: int

  NALLOC = 1024;

  // morecore :: (uint) -> *header

  morecore = function(nu) { // :: (uint)
    var bytesNeeded, up;
    if (nu < NALLOC) {
      nu = NALLOC;
    }
    bytesNeeded = nu * 8;
    if (_U32[0] + bytesNeeded >= _U8.length) {
      return null;
    }
    // up :: *header
    up = _U32[0] >> 2;
    _U32[up + 1] = nu;
    _U32[0] += bytesNeeded;
    free(up + 1 * 2 << 2);
    return freep;
  };

  // free :: (*any) -> any

  free = function(ap) { // :: (*any)
    var bp, p;
    // bp, p :: *header
    bp = (ap >> 2) - 1 * 2;
    p = freep;
    while (!(bp > p && bp < _U32[p])) {
      if (p >= _U32[p] && (bp > p || bp < _U32[p])) {
        break;
      }
      p = _U32[p];
    }
    if (bp + _U32[bp + 1] * 2 === _U32[p]) {
      _U32[bp + 1] += _U32[_U32[p] + 1];
      _U32[bp] = _U32[_U32[p]];
    } else {
      _U32[bp] = _U32[p];
    }
    if (p + _U32[p + 1] * 2 === bp) {
      _U32[p + 1] += _U32[bp + 1];
      _U32[p] = _U32[bp];
    } else {
      _U32[p] = bp;
    }
    freep = p;
  };

  exports.malloc = malloc;

  exports.free = free;

  var p = malloc(32);
  console.log(p);
  var p = malloc(32);
  console.log(p);
  var p = malloc(32);
  console.log(p);

}).call(this);
